version:  '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: node-frontend-agricola
    container_name: frontend
    ports:
      - "3331:3000"
    volumes:
      - ./frontend:/app
    depends_on: 
      - backend
    command: npm run dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: node-backend-agricola
    container_name: backend
    ports:
      - "3332:3000"
    volumes:
      - ./backend:/app
    command: npm run dev

  mongodb:
    image: mongo
    container_name: mongo-agricola
    restart: always
    ports:
      - "27277:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: senha123
      MONGO_INITDB_ROOT_DATABASE: agricola

  mongoexpress:
    image: mongo-express
    container_name: mongo-express-agricola
    restart: always
    ports:
      - "8881:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: senha123
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: senha123
    depends_on:
      - mongodb

volumes:
  mongo-data: